import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body className="bg-gray-50 text-gray-900">
                <header className="bg-blue-800 text-white py-4 px-6 shadow-md">
                    <h1 className="text-3xl font-bold">Simulation de Routage</h1>
                </header>
                <main className="flex flex-col md:flex-row">
                    <aside className="w-full md:w-64 bg-white p-6 border-r border-gray-200">
                        <h2 className="text-xl font-semibold mb-4">Paramètres</h2>
                        {/* Par exemple, le menu de sélection de stratégie */}
                    </aside>
                    <section className="flex-1 p-6">
                        {children}
                    </section>
                </main>
                <footer className="bg-gray-200 text-gray-700 py-3 text-center">
                    &copy; 2025 Robot Meet Art
                </footer>
            </body>
        </html>
    );
}
